import { pgTable, uuid, varchar, text, boolean, smallint, integer, numeric, timestamp } from 'drizzle-orm/pg-core';

export const branches = pgTable('branches', {
  id:            uuid('id').primaryKey().defaultRandom(),
  orgId:         uuid('org_id').notNull(),
  name:          varchar('name', { length: 300 }).notNull(),
  code:          varchar('code', { length: 20 }),
  branchType:    varchar('branch_type', { length: 50 }),
  description:   text('description'),
  addressLine1:  varchar('address_line1', { length: 500 }),
  addressLine2:  varchar('address_line2', { length: 500 }),
  cityId:        integer('city_id'),
  stateId:       smallint('state_id'),
  countryId:     smallint('country_id'),
  pincode:       varchar('pincode', { length: 10 }),
  latitude:      numeric('latitude'),
  longitude:     numeric('longitude'),
  phone:         varchar('phone', { length: 20 }),
  email:         varchar('email', { length: 255 }),
  gstin:         varchar('gstin', { length: 20 }),
  managerUserId: uuid('manager_user_id'),
  isHq:          boolean('is_hq').default(false).notNull(),
  employeeCount: integer('employee_count'),
  isActive:      boolean('is_active').default(true).notNull(),
  deletedAt:     timestamp('deleted_at', { withTimezone: true }),
  createdBy:     uuid('created_by'),
  updatedBy:     uuid('updated_by'),
  createdAt:     timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt:     timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});