import { pgTable, uuid, varchar, text, boolean, integer, timestamp, } from 'drizzle-orm/pg-core';

export const organizations = pgTable('organizations', {
  id:                   uuid('id').primaryKey().defaultRandom(),
  name:                 varchar('name', { length: 300 }).notNull(),
  legalName:            varchar('legal_name', { length: 300 }),
  shortCode:            varchar('short_code', { length: 20 }),
  logoUrl:              text('logo_url'),
  website:              varchar('website', { length: 500 }),
  description:          text('description'),
  gstin:                varchar('gstin', { length: 20 }),
  pan:                  varchar('pan', { length: 20 }),
  cin:                  varchar('cin', { length: 30 }),
  tan:                  varchar('tan', { length: 20 }),
  msmeNumber:           varchar('msme_number', { length: 50 }),
  primaryEmail:         varchar('primary_email', { length: 255 }),
  primaryPhone:         varchar('primary_phone', { length: 20 }),
  supportEmail:         varchar('support_email', { length: 255 }),
  supportPhone:         varchar('support_phone', { length: 20 }),
  addressLine1:         varchar('address_line1', { length: 500 }),
  addressLine2:         varchar('address_line2', { length: 500 }),
  city:                 varchar('city', { length: 100 }),
  state:                varchar('state', { length: 100 }),
  country:              varchar('country', { length: 60 }),
  pincode:              varchar('pincode', { length: 10 }),
  timezone:             varchar('timezone', { length: 60 }),
  currencyCode:         varchar('currency_code', { length: 10 }),
  currencySymbol:       varchar('currency_symbol', { length: 5 }),
  dateFormat:           varchar('date_format', { length: 20 }),
  fiscalYearStart:      varchar('fiscal_year_start', { length: 10 }),
  financialYearLabel:   varchar('financial_year_label', { length: 20 }),
  assetIdPrefix:        varchar('asset_id_prefix', { length: 20 }),
  depreciationMethod:   varchar('depreciation_method', { length: 30 }),
  defaultAssetLifeYears:integer('default_asset_life_years'),
  isActive:             boolean('is_active').default(true).notNull(),
  isVerified:           boolean('is_verified').default(false).notNull(),
  onboardedAt:          timestamp('onboarded_at', { withTimezone: true }),
  deletedAt:            timestamp('deleted_at', { withTimezone: true }),
  createdBy:            uuid('created_by'),
  updatedBy:            uuid('updated_by'),
  createdAt:            timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt:            timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});