import {
  pgTable, uuid, varchar, text, boolean, smallint,
  timestamp, date, inet,
} from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id:                   uuid('id').primaryKey().defaultRandom(),
  orgId:                uuid('org_id').notNull(),
  employeeId:           varchar('employee_id', { length: 50 }),
  firstName:            varchar('first_name', { length: 100 }).notNull(),
  lastName:             varchar('last_name',  { length: 100 }),
  displayName:          varchar('display_name', { length: 200 }),
  email:                varchar('email',    { length: 255 }).notNull(),
  username:             varchar('username', { length: 100 }),
  passwordHash:         text('password_hash'),
  passwordChangedAt:    timestamp('password_changed_at', { withTimezone: true }),
  mustChangePassword:   boolean('must_change_password').default(false).notNull(),
  departmentId:         uuid('department_id'),
  designationId:        uuid('designation_id'),
  branchId:             uuid('branch_id'),
  locationId:           uuid('location_id'),
  reportingManagerId:   uuid('reporting_manager_id'),
  joiningDate:          date('joining_date'),
  workEmail:            varchar('work_email', { length: 255 }),
  workPhone:            varchar('work_phone', { length: 20 }),
  mobile:               varchar('mobile',    { length: 20 }),
  extension:            varchar('extension', { length: 10 }),
  avatarUrl:            text('avatar_url'),
  avatarThumbUrl:       text('avatar_thumb_url'),
  status:               varchar('status', { length: 30 }).default('active'),
  isActive:             boolean('is_active').default(true).notNull(),
  failedLoginAttempts:  smallint('failed_login_attempts').default(0),
  lockedUntil:          timestamp('locked_until',     { withTimezone: true }),
  lastLoginAt:          timestamp('last_login_at',    { withTimezone: true }),
  lastLoginIp:          inet('last_login_ip'),
  lastActiveAt:         timestamp('last_active_at',   { withTimezone: true }),
  timezone:             varchar('timezone', { length: 50 }),
  locale:               varchar('locale',   { length: 10 }),
  theme:                varchar('theme',    { length: 20 }),
  notificationEmail:    boolean('notification_email').default(true),
  notificationInapp:    boolean('notification_inapp').default(true),
  deletedAt:            timestamp('deleted_at',      { withTimezone: true }),
  deletedBy:            uuid('deleted_by'),
  offboardedAt:         timestamp('offboarded_at',   { withTimezone: true }),
  offboardedBy:         uuid('offboarded_by'),
  createdBy:            uuid('created_by'),
  updatedBy:            uuid('updated_by'),
  createdAt:            timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt:            timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});